# Generated by Django 3.2.9 on 2021-11-14 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actioncountapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dumb',
            fields=[
                ('dumbcount', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Fat',
            fields=[
                ('fatcount', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Stupid',
            fields=[
                ('stupidcount', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.DeleteModel(
            name='Count',
        ),
    ]
